version: '3.8'

services:

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
    command: /app/run.sh

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: /app/run-celery.sh
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      - django

  celery-beat:
    build: .
    command: /app/run-celery-beat.sh
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      - django

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - django

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.example
    ports:
      - "5432:5432"

volumes:
  postgres_data: